# Generated by Django 4.2.4 on 2023-08-10 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Roads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblazs',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tblroads',
            options={'managed': False},
        ),
    ]
